name: Fetch arXiv rss

on:
  workflow_dispatch:
  schedule:
    - cron: '5 0 * * *'  # Run this workflow every day at 00:05 UTC

jobs:
  fetch-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Fetch the XML data
      run: |
        curl https://rss.arxiv.org/rss/cs.CV > "${{ github.workspace }}/xml/$(date +'%Y-%m-%d')-cs-cv.xml"
        curl https://rss.arxiv.org/rss/cs.AI > "${{ github.workspace }}/xml/$(date +'%Y-%m-%d')-cs-ai.xml"
        curl https://rss.arxiv.org/rss/cs.CL > "${{ github.workspace }}/xml/$(date +'%Y-%m-%d')-cs-cl.xml"
        curl https://rss.arxiv.org/rss/cs.LG > "${{ github.workspace }}/xml/$(date +'%Y-%m-%d')-cs-lg.xml"

    - name: Run converter.py script
      working-directory: ${{ github.workspace }}
      run: |
        python converter.py
        python generate_index.py

    - name: Commit and push
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Action"
        git add .
        git commit -m "Updated arxiv data"
        git push
