name: Fetch arXiv rss

on:
  schedule:
    - cron: '5 0 * * *'  # Run this workflow every day at 00:00 UTC

jobs:
  fetch-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Fetch the XML data
      run: |
        curl https://export.arxiv.org/rss/cs.CV > "$(date +'%Y-%m-%d')-cs-cv.xml"
        curl https://export.arxiv.org/rss/cs.AI > "$(date +'%Y-%m-%d')-cs-ai.xml"
        curl https://export.arxiv.org/rss/cs.CL > "$(date +'%Y-%m-%d')-cs-cl.xml"
        curl https://export.arxiv.org/rss/cs.LG > "$(date +'%Y-%m-%d')-cs-lg.xml"

    - name: Commit and push if it changed
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Action"
        git diff --quiet || (git add . ; git commit -m "Updated arxiv data" ; git push)

